hostname="fw"
sshd_enable="YES"
ifconfig_em0="inet 172.16.90.1 netmask 255.255.255.0"
ifconfig_em1="inet 192.168.56.254 netmask 255.255.255.0"
ifconfig_em2="inet 192.168.57.254 netmask 255.255.255.0"
gateway_enable="YES"
firewall_enable="YES"
firewall_script="/root/firewall_ipfw.sh"
firewall_logging="YES"
ntpd_enable="YES"
ntpd_flags="-g"
ntpdate_enable="YES"
ntpdate_hosts="a.ntp.br"
